In [2]:
import pandas as pd
import numpy as np
from scipy import stats as st
data = [
    {"RollNo": 1, "FirstName": "John", "LastName": "Doe", "Gender": "Male", "Div": "A", "Grade": "A", "Attendance": 90.0},
    {"RollNo": 2, "FirstName": "Jane", "LastName": "Smith", "Gender": "Female", "Div": "B", "Grade": "B+", "Attendance": 85.0},
    {"RollNo": 3, "FirstName": "Mike", "LastName": "Johnson", "Gender": "Male", "Div": "C", "Grade": "B", "Attendance": 78.0},
    {"RollNo": 4, "FirstName": "Amy", "LastName": "Williams", "Gender": "Female", "Div": "A", "Grade": "A", "Attendance": 95.0},
    {"RollNo": 5, "FirstName": "Chris", "LastName": "Brown", "Gender": "Male", "Div": "B", "Grade": "C", "Attendance": 88.0},
    {"RollNo": 6, "FirstName": "Anna", "LastName": "Wilson", "Gender": "Female", "Div": "1", "Grade": "A", "Attendance": 85.0},
    {"RollNo": 7, "FirstName": "David", "LastName": "Moore", "Gender": "Male", "Div": "A", "Grade": "B", "Attendance": 130.0},
    {"RollNo": 8, "FirstName": "Susan", "LastName": "Taylor", "Gender": "Female", "Div": "B", "Grade": "C", "Attendance": 70.0},
    {"RollNo": 9, "FirstName": "James", "LastName": "Anderson", "Gender": "Male", "Div": "C", "Grade": "A", "Attendance": 80.0},
    {"RollNo": 10, "FirstName": "Linda", "LastName": "Harris", "Gender": "Female", "Div": "A", "Grade": "B+", "Attendance": 75.0},
    {"RollNo": 11, "FirstName": "Patricia", "LastName": "Martin", "Gender": "Female", "Div": "C", "Grade": "C", "Attendance": 93.0},
    {"RollNo": 12, "FirstName": "Robert", "LastName": "Lee", "Gender": "Male", "Div": "A", "Grade": "A", "Attendance": 85.0},
    {"RollNo": 13, "FirstName": "Lisa", "LastName": "Walker", "Gender": "Female", "Div": "B", "Grade": "B", "Attendance": 4.0},
    {"RollNo": 14, "FirstName": "Michael", "LastName": "Young", "Gender": "Male", "Div": "C", "Grade": "C", "Attendance": 90.0},
    {"RollNo": 15, "FirstName": "Sarah", "LastName": "King", "Gender": "Female", "Div": "A", "Grade": "A", "Attendance": 88.0},
    {"RollNo": 16, "FirstName": "Daniel", "LastName": "Scott", "Gender": "Male", "Div": "B", "Grade": "B", "Attendance": None},
    {"RollNo": 17, "FirstName": "Thomas", "LastName": "Jackson", "Gender": "Female", "Div": "C", "Grade": "A", "Attendance": 98.0},
    {"RollNo": 18, "FirstName": "Jessica", "LastName": "White", "Gender": "Female", "Div": "A", "Grade": "B", "Attendance": 10.0},
    {"RollNo": 19, "FirstName": "William", "LastName": "Hernandez", "Gender": "Male", "Div": "C", "Grade": "C", "Attendance": 72.0},
    {"RollNo": 20, "FirstName": "Emily", "LastName": "Brown", "Gender": "Female", "Div": "A", "Grade": "A", "Attendance": 85.0}
]
df=pd.DataFrame(data)
df

    RollNo FirstName   LastName  Gender Div Grade  Attendance
0        1      John        Doe    Male   A     A        90.0
1        2      Jane      Smith  Female   B    B+        85.0
2        3      Mike    Johnson    Male   C     B        78.0
3        4       Amy   Williams  Female   A     A        95.0
4        5     Chris      Brown    Male   B     C        88.0
5        6      Anna     Wilson  Female   1     A        85.0
6        7     David      Moore    Male   A     B       130.0
7        8     Susan     Taylor  Female   B     C        70.0
8        9     James   Anderson    Male   C     A        80.0
9       10     Linda     Harris  Female   A    B+        75.0
10      11  Patricia     Martin  Female   C     C        93.0
11      12    Robert        Lee    Male   A     A        85.0
12      13      Lisa     Walker  Female   B     B         4.0
13      14   Michael      Young    Male   C     C        90.0
14      15     Sarah       King  Female   A     A        88.0
15      16    Daniel      Scott    Male   B     B         NaN
16      17    Thomas    Jackson  Female   C     A        98.0
17      18   Jessica      White  Female   A     B        10.0
18      19   William  Hernandez    Male   C     C        72.0
19      20     Emily      Brown  Female   A     A        85.0

In [3]:
df.isnull().sum()

RollNo        0
FirstName     0
LastName      0
Gender        0
Div           0
Grade         0
Attendance    1
dtype: int64

In [4]:
df.dtypes

RollNo          int64
FirstName      object
LastName       object
Gender         object
Div            object
Grade          object
Attendance    float64
dtype: object

In [5]:
df.bfill()

    RollNo FirstName   LastName  Gender Div Grade  Attendance
0        1      John        Doe    Male   A     A        90.0
1        2      Jane      Smith  Female   B    B+        85.0
2        3      Mike    Johnson    Male   C     B        78.0
3        4       Amy   Williams  Female   A     A        95.0
4        5     Chris      Brown    Male   B     C        88.0
5        6      Anna     Wilson  Female   1     A        85.0
6        7     David      Moore    Male   A     B       130.0
7        8     Susan     Taylor  Female   B     C        70.0
8        9     James   Anderson    Male   C     A        80.0
9       10     Linda     Harris  Female   A    B+        75.0
10      11  Patricia     Martin  Female   C     C        93.0
11      12    Robert        Lee    Male   A     A        85.0
12      13      Lisa     Walker  Female   B     B         4.0
13      14   Michael      Young    Male   C     C        90.0
14      15     Sarah       King  Female   A     A        88.0
15      16    Daniel      Scott    Male   B     B        98.0
16      17    Thomas    Jackson  Female   C     A        98.0
17      18   Jessica      White  Female   A     B        10.0
18      19   William  Hernandez    Male   C     C        72.0
19      20     Emily      Brown  Female   A     A        85.0

In [6]:
df.isnull().sum()

RollNo        0
FirstName     0
LastName      0
Gender        0
Div           0
Grade         0
Attendance    1
dtype: int64

In [7]:
df['Div'].value_counts()

Div
A    8
C    6
B    5
1    1
Name: count, dtype: int64

In [8]:
df['Div'].replace({'1':'A'})

0     A
1     B
2     C
3     A
4     B
5     A
6     A
7     B
8     C
9     A
10    C
11    A
12    B
13    C
14    A
15    B
16    C
17    A
18    C
19    A
Name: Div, dtype: object

In [34]:
Q1 = df['Attendance'].quantile(0.25)
Q3 = df['Attendance'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[
    ((df['Attendance'] < (Q1 - 1.5 * IQR)) |
      (df['Attendance'] > (Q3 + 1.5 * IQR)))
]

In [35]:
print(outliers)

      RollNo FirstName LastName  Gender Div Grade  Attendance
6   0.315789     David    Moore    Male   A     B       130.0
12  0.631579      Lisa   Walker  Female   B     B         4.0
17  0.894737   Jessica    White  Female   A     B        10.0

In [36]:
df['RollNo'] = (df['RollNo']- df['RollNo'].min()) / (df['RollNo'].max()-df['RollNo'].min())

In [37]:
df['RollNo'] = (df['RollNo']- df['RollNo'].min()) / (df['RollNo'].max()-df['RollNo'].min())

In [38]:
df

      RollNo FirstName   LastName  Gender Div Grade  Attendance
0   0.000000      John        Doe    Male   A     A        90.0
1   0.052632      Jane      Smith  Female   B    B+        85.0
2   0.105263      Mike    Johnson    Male   C     B        78.0
3   0.157895       Amy   Williams  Female   A     A        95.0
4   0.210526     Chris      Brown    Male   B     C        88.0
5   0.263158      Anna     Wilson  Female   1     A        85.0
6   0.315789     David      Moore    Male   A     B       130.0
7   0.368421     Susan     Taylor  Female   B     C        70.0
8   0.421053     James   Anderson    Male   C     A        80.0
9   0.473684     Linda     Harris  Female   A    B+        75.0
10  0.526316  Patricia     Martin  Female   C     C        93.0
11  0.578947    Robert        Lee    Male   A     A        85.0
12  0.631579      Lisa     Walker  Female   B     B         4.0
13  0.684211   Michael      Young    Male   C     C        90.0
14  0.736842     Sarah       King  Female   A     A        88.0
15  0.789474    Daniel      Scott    Male   B     B         NaN
16  0.842105    Thomas    Jackson  Female   C     A        98.0
17  0.894737   Jessica      White  Female   A     B        10.0
18  0.947368   William  Hernandez    Male   C     C        72.0
19  1.000000     Emily      Brown  Female   A     A        85.0

In [39]:
df['Attendance'] = (df['Attendance']- df['Attendance'].mean()) /(df['Attendance'].std())

In [40]:
df

      RollNo FirstName   LastName  Gender Div Grade  Attendance
0   0.000000      John        Doe    Male   A     A    0.387619
1   0.052632      Jane      Smith  Female   B    B+    0.211428
2   0.105263      Mike    Johnson    Male   C     B   -0.035238
3   0.157895       Amy   Williams  Female   A     A    0.563809
4   0.210526     Chris      Brown    Male   B     C    0.317143
5   0.263158      Anna     Wilson  Female   1     A    0.211428
6   0.315789     David      Moore    Male   A     B    1.797142
7   0.368421     Susan     Taylor  Female   B     C   -0.317143
8   0.421053     James   Anderson    Male   C     A    0.035238
9   0.473684     Linda     Harris  Female   A    B+   -0.140952
10  0.526316  Patricia     Martin  Female   C     C    0.493333
11  0.578947    Robert        Lee    Male   A     A    0.211428
12  0.631579      Lisa     Walker  Female   B     B   -2.642856
13  0.684211   Michael      Young    Male   C     C    0.387619
14  0.736842     Sarah       King  Female   A     A    0.317143
15  0.789474    Daniel      Scott    Male   B     B         NaN
16  0.842105    Thomas    Jackson  Female   C     A    0.669523
17  0.894737   Jessica      White  Female   A     B   -2.431427
18  0.947368   William  Hernandez    Male   C     C   -0.246667
19  1.000000     Emily      Brown  Female   A     A    0.211428

In [41]:
outliers = df[abs(df['Attendance']) > 1]
outliers

      RollNo FirstName LastName  Gender Div Grade  Attendance
6   0.315789     David    Moore    Male   A     B    1.797142
12  0.631579      Lisa   Walker  Female   B     B   -2.642856
17  0.894737   Jessica    White  Female   A     B   -2.431427